<?php

use App\User;
use Illuminate\Database\Seeder;

class UsersTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        User::truncate();       

        // $user = new User; $user->name = 'Integras - Odontologo'; $user->email = 'Integras@gmail.com'; $user->password = bcrypt('12345678'); $user->save();
        // $user = new User; $user->id = '132'; $user->name = 'REVOLLO EDUARDO'; $user->email = 'odonto132@gmail.com'; $user->password = bcrypt('12345678'); $user->save();
        // $user = new User; $user->id = '133'; $user->name = 'DIAZ RODOLFO IVAN'; $user->email = 'odonto133@gmail.com'; $user->password = bcrypt('12345678'); $user->save();
        // $user = new User; $user->id = '134'; $user->name = 'VELANDIA EFRAIN'; $user->email = 'odonto134@gmail.com'; $user->password = bcrypt('12345678'); $user->save();
        // $user = new User; $user->id = '135'; $user->name = 'JAIMES LINA'; $user->email = 'odonto135@gmail.com'; $user->password = bcrypt('12345678'); $user->save();
        // $user = new User; $user->id = '136'; $user->name = 'ESPINOZA CLAUDIA MARCELA'; $user->email = 'odonto136@gmail.com'; $user->password = bcrypt('12345678'); $user->save();
        // $user = new User; $user->id = '137'; $user->name = 'DIAZ DIANA'; $user->email = 'odonto137@gmail.com'; $user->password = bcrypt('12345678'); $user->save();
        // $user = new User; $user->id = '138'; $user->name = 'ANGARITA MAIRA ALEJANDRA'; $user->email = 'odonto138@gmail.com'; $user->password = bcrypt('12345678'); $user->save();
        // $user = new User; $user->id = '139'; $user->name = 'PACHECO APARICIO JOHANA'; $user->email = 'odonto139@gmail.com'; $user->password = bcrypt('12345678'); $user->save();
        // $user = new User; $user->id = '140'; $user->name = 'TENORIO FABIAN'; $user->email = 'odonto140@gmail.com'; $user->password = bcrypt('12345678'); $user->save();
        // $user = new User; $user->id = '141'; $user->name = 'GUZMAN JUAN PABLO'; $user->email = 'odonto141@gmail.com'; $user->password = bcrypt('12345678'); $user->save();
        // $user = new User; $user->id = '142'; $user->name = 'DIAZ JULIAN'; $user->email = 'odonto142@gmail.com'; $user->password = bcrypt('12345678'); $user->save();
        // $user = new User; $user->id = '143'; $user->name = 'LONDOÃ‘O GERMAN'; $user->email = 'odonto143@gmail.com'; $user->password = bcrypt('12345678'); $user->save();
        // $user = new User; $user->id = '144'; $user->name = 'FLOREZ JESSICA'; $user->email = 'odonto144@gmail.com'; $user->password = bcrypt('12345678'); $user->save();
        // $user = new User; $user->id = '145'; $user->name = 'BOLAÃ‘OS ANGELICA'; $user->email = 'odonto145@gmail.com'; $user->password = bcrypt('12345678'); $user->save();
        // $user = new User; $user->id = '146'; $user->name = 'QUINTERO MARIA FERNANDA'; $user->email = 'odonto146@gmail.com'; $user->password = bcrypt('12345678'); $user->save();
        // $user = new User; $user->id = '147'; $user->name = 'HERNANDEZ MARCO'; $user->email = 'odonto147@gmail.com'; $user->password = bcrypt('12345678'); $user->save();
        // $user = new User; $user->id = '148'; $user->name = 'VALVERDE ALBA DAMARIS'; $user->email = 'odonto148@gmail.com'; $user->password = bcrypt('12345678'); $user->save();
        // $user = new User; $user->id = '149'; $user->name = 'OSORIO GUILLERMO'; $user->email = 'odonto149@gmail.com'; $user->password = bcrypt('12345678'); $user->save();
        // $user = new User; $user->id = '150'; $user->name = 'CASTAÃ‘EDA PAULA'; $user->email = 'odonto150@gmail.com'; $user->password = bcrypt('12345678'); $user->save();
        // $user = new User; $user->id = '151'; $user->name = 'POZO TATIANA'; $user->email = 'odonto151@gmail.com'; $user->password = bcrypt('12345678'); $user->save();
        // $user = new User; $user->id = '152'; $user->name = 'ISAZA ALVAREZ VERONICA'; $user->email = 'odonto152@gmail.com'; $user->password = bcrypt('12345678'); $user->save();
        // $user = new User; $user->id = '153'; $user->name = 'BAPTISTA ELIZABETH'; $user->email = 'odonto153@gmail.com'; $user->password = bcrypt('12345678'); $user->save();
        // $user = new User; $user->id = '154'; $user->name = 'MARTINEZ PEREZ JACKELINE'; $user->email = 'odonto154@gmail.com'; $user->password = bcrypt('12345678'); $user->save();
        // $user = new User; $user->id = '155'; $user->name = 'AVILA RENGIFO JULIAN ARLEY'; $user->email = 'odonto155@gmail.com'; $user->password = bcrypt('12345678'); $user->save();
        // $user = new User; $user->id = '156'; $user->name = 'PUERTAS PUERTA ANGELICA MARIA'; $user->email = 'odonto156@gmail.com'; $user->password = bcrypt('12345678'); $user->save();
        // $user = new User; $user->id = '157'; $user->name = 'VELEZ MARIA FERNANDA'; $user->email = 'odonto157@gmail.com'; $user->password = bcrypt('12345678'); $user->save();
        // $user = new User; $user->id = '158'; $user->name = 'CHAPARRO JUAN JOSE'; $user->email = 'odonto158@gmail.com'; $user->password = bcrypt('12345678'); $user->save();
        // $user = new User; $user->id = '159'; $user->name = 'GOMEZ NESTOR JAIRO'; $user->email = 'odonto159@gmail.com'; $user->password = bcrypt('12345678'); $user->save();
        // $user = new User; $user->id = '160'; $user->name = 'CUADROS GIL CLAUDIA'; $user->email = 'odonto160@gmail.com'; $user->password = bcrypt('12345678'); $user->save();
        // $user = new User; $user->id = '162'; $user->name = 'LOZADA KAREN'; $user->email = 'odonto162@gmail.com'; $user->password = bcrypt('12345678'); $user->save();
        // $user = new User; $user->id = '164'; $user->name = 'DEHAKIZ LUIS FERNANDO'; $user->email = 'odonto164@gmail.com'; $user->password = bcrypt('12345678'); $user->save();
        // $user = new User; $user->id = '165'; $user->name = 'RODRIGUEZ ALEXANDER'; $user->email = 'odonto165@gmail.com'; $user->password = bcrypt('12345678'); $user->save();
        // $user = new User; $user->id = '166'; $user->name = 'ESCOBAR FREDY'; $user->email = 'odonto166@gmail.com'; $user->password = bcrypt('12345678'); $user->save();
        // $user = new User; $user->id = '167'; $user->name = 'BUITRAGO JAIMES JAIRO'; $user->email = 'odonto167@gmail.com'; $user->password = bcrypt('12345678'); $user->save();
        // $user = new User; $user->id = '310'; $user->name = 'FORERO FABIAN'; $user->email = 'odonto310@gmail.com'; $user->password = bcrypt('12345678'); $user->save();
        // $user = new User; $user->id = '163'; $user->name = 'BENAVIDES OSCAR'; $user->email = 'odonto163@gmail.com'; $user->password = bcrypt('12345678'); $user->save();
        // $user = new User; $user->id = '161'; $user->name = 'CUBIDES ESPERANZA'; $user->email = 'odonto161@gmail.com'; $user->password = bcrypt('12345678'); $user->save();
        // $user = new User; $user->id = '170'; $user->name = 'ARANDA ANDRES'; $user->email = 'odonto170@gmail.com'; $user->password = bcrypt('12345678'); $user->save();
        // $user = new User; $user->id = '171'; $user->name = 'LOPEZ DIEGO FERNANDO'; $user->email = 'odonto171@gmail.com'; $user->password = bcrypt('12345678'); $user->save();
        // $user = new User; $user->id = '172'; $user->name = 'MALAGON GONZALEZ ELIANA YANETH'; $user->email = 'odonto172@gmail.com'; $user->password = bcrypt('12345678'); $user->save();
        // $user = new User; $user->id = '173'; $user->name = 'PINEDA PATRICIA'; $user->email = 'odonto173@gmail.com'; $user->password = bcrypt('12345678'); $user->save();
        // $user = new User; $user->id = '174'; $user->name = 'ROBLES JAIR ESTEBAN'; $user->email = 'odonto174@gmail.com'; $user->password = bcrypt('12345678'); $user->save();
        // $user = new User; $user->id = '175'; $user->name = 'VELEZ LEYLA MARIA'; $user->email = 'odonto175@gmail.com'; $user->password = bcrypt('12345678'); $user->save();
        // $user = new User; $user->id = '176'; $user->name = 'SOLARTE YOLANDA'; $user->email = 'odonto176@gmail.com'; $user->password = bcrypt('12345678'); $user->save();
        // $user = new User; $user->id = '177'; $user->name = 'VALENCIA GUSTAVO'; $user->email = 'odonto177@gmail.com'; $user->password = bcrypt('12345678'); $user->save();
        // $user = new User; $user->id = '179'; $user->name = 'HENAO CAROLINA'; $user->email = 'odonto179@gmail.com'; $user->password = bcrypt('12345678'); $user->save();
        // $user = new User; $user->id = '180'; $user->name = 'SALAZAR MARIO GERMAN'; $user->email = 'odonto180@gmail.com'; $user->password = bcrypt('12345678'); $user->save();
        // $user = new User; $user->id = '181'; $user->name = 'HINCAPIE MARIA HELENA'; $user->email = 'odonto181@gmail.com'; $user->password = bcrypt('12345678'); $user->save();
        // $user = new User; $user->id = '182'; $user->name = 'PAREDES JAIME HERNAN'; $user->email = 'odonto182@gmail.com'; $user->password = bcrypt('12345678'); $user->save();
        // $user = new User; $user->id = '183'; $user->name = 'FORERO DIANA CONSTANZA'; $user->email = 'odonto183@gmail.com'; $user->password = bcrypt('12345678'); $user->save();
        // $user = new User; $user->id = '184'; $user->name = 'ANDRADE NATALIA'; $user->email = 'odonto184@gmail.com'; $user->password = bcrypt('12345678'); $user->save();
        // $user = new User; $user->id = '186'; $user->name = 'PEREZ ALEXANDER'; $user->email = 'odonto186@gmail.com'; $user->password = bcrypt('12345678'); $user->save();
        // $user = new User; $user->id = '187'; $user->name = 'ARISTIZABAL LINA MARIA'; $user->email = 'odonto187@gmail.com'; $user->password = bcrypt('12345678'); $user->save();
        // $user = new User; $user->id = '188'; $user->name = 'SALAZAR SANTIAGO'; $user->email = 'odonto188@gmail.com'; $user->password = bcrypt('12345678'); $user->save();
        // $user = new User; $user->id = '189'; $user->name = 'CAMPO SONIA ROSA'; $user->email = 'odonto189@gmail.com'; $user->password = bcrypt('12345678'); $user->save();
        // $user = new User; $user->id = '190'; $user->name = 'SUA MONICA'; $user->email = 'odonto190@gmail.com'; $user->password = bcrypt('12345678'); $user->save();
        // $user = new User; $user->id = '191'; $user->name = 'BERNAL JORGE'; $user->email = 'odonto191@gmail.com'; $user->password = bcrypt('12345678'); $user->save();
        // $user = new User; $user->id = '192'; $user->name = 'ALFONSO RAYZA ALEJANDRA'; $user->email = 'odonto192@gmail.com'; $user->password = bcrypt('12345678'); $user->save();
        // $user = new User; $user->id = '193'; $user->name = 'CARDONA JOAN'; $user->email = 'odonto193@gmail.com'; $user->password = bcrypt('12345678'); $user->save();
        // $user = new User; $user->id = '194'; $user->name = 'GARCIA DIANA'; $user->email = 'odonto194@gmail.com'; $user->password = bcrypt('12345678'); $user->save();
        // $user = new User; $user->id = '195'; $user->name = 'OCAMPO YULIANA'; $user->email = 'odonto195@gmail.com'; $user->password = bcrypt('12345678'); $user->save();
        // $user = new User; $user->id = '196'; $user->name = 'OSORIO HUGO FERNANDO'; $user->email = 'odonto196@gmail.com'; $user->password = bcrypt('12345678'); $user->save();
        // $user = new User; $user->id = '197'; $user->name = 'BURBANO ALEXANDER'; $user->email = 'odonto197@gmail.com'; $user->password = bcrypt('12345678'); $user->save();
        // $user = new User; $user->id = '198'; $user->name = 'ALDANA FELIPE ANDRES'; $user->email = 'odonto198@gmail.com'; $user->password = bcrypt('12345678'); $user->save();
        // $user = new User; $user->id = '199'; $user->name = 'ZULUAGA ROJAS CATALINA'; $user->email = 'odonto199@gmail.com'; $user->password = bcrypt('12345678'); $user->save();
        // $user = new User; $user->id = '202'; $user->name = 'NOREÃ‘A SORIANO CARLOS ALBERTO'; $user->email = 'odonto202@gmail.com'; $user->password = bcrypt('12345678'); $user->save();
        // $user = new User; $user->id = '200'; $user->name = 'GIL JESUS DAVID'; $user->email = 'odonto200@gmail.com'; $user->password = bcrypt('12345678'); $user->save();
        // $user = new User; $user->id = '201'; $user->name = 'YEPES CORTEZ ANGELA VIVIANA'; $user->email = 'odonto201@gmail.com'; $user->password = bcrypt('12345678'); $user->save();
        // $user = new User; $user->id = '203'; $user->name = 'RUIZ ALBA DIANA MARCELA'; $user->email = 'odonto203@gmail.com'; $user->password = bcrypt('12345678'); $user->save();
        // $user = new User; $user->id = '204'; $user->name = 'HOLGUIN JUAN CARLOS'; $user->email = 'odonto204@gmail.com'; $user->password = bcrypt('12345678'); $user->save();
        // $user = new User; $user->id = '205'; $user->name = 'DEVIA YINETH JULIANA'; $user->email = 'odonto205@gmail.com'; $user->password = bcrypt('12345678'); $user->save();
        // $user = new User; $user->id = '206'; $user->name = 'SANTIAGO STEPHANIE KARLEY'; $user->email = 'odonto206@gmail.com'; $user->password = bcrypt('12345678'); $user->save();
        // $user = new User; $user->id = '185'; $user->name = 'MENESES LUIS MARIO'; $user->email = 'odonto185@gmail.com'; $user->password = bcrypt('12345678'); $user->save();
        // $user = new User; $user->id = '178'; $user->name = 'GARCIA FERNANDO'; $user->email = 'odonto178@gmail.com'; $user->password = bcrypt('12345678'); $user->save();
        // $user = new User; $user->id = '208'; $user->name = 'RAMIREZ RESTREPO RODRIGO'; $user->email = 'odonto208@gmail.com'; $user->password = bcrypt('12345678'); $user->save();
        // $user = new User; $user->id = '209'; $user->name = 'MESA BENITEZ CARLOS EDUARDO'; $user->email = 'odonto209@gmail.com'; $user->password = bcrypt('12345678'); $user->save();
        // $user = new User; $user->id = '210'; $user->name = 'CUARTAS SORIANA DAVID'; $user->email = 'odonto210@gmail.com'; $user->password = bcrypt('12345678'); $user->save();
        // $user = new User; $user->id = '211'; $user->name = 'OCAMPO ANGELICA'; $user->email = 'odonto211@gmail.com'; $user->password = bcrypt('12345678'); $user->save();
        // $user = new User; $user->id = '212'; $user->name = 'GONZALIAS YORLY LORENA'; $user->email = 'odonto212@gmail.com'; $user->password = bcrypt('12345678'); $user->save();
        // $user = new User; $user->id = '213'; $user->name = 'LOAIZA SANDRA MILENA'; $user->email = 'odonto213@gmail.com'; $user->password = bcrypt('12345678'); $user->save();
        // $user = new User; $user->id = '214'; $user->name = 'CORREA LUIS ENRIQUE'; $user->email = 'odonto214@gmail.com'; $user->password = bcrypt('12345678'); $user->save();
        // $user = new User; $user->id = '215'; $user->name = 'GOMEZ GLORIA DEL SOCORRO'; $user->email = 'odonto215@gmail.com'; $user->password = bcrypt('12345678'); $user->save();
        // $user = new User; $user->id = '216'; $user->name = 'MONTOYA ANGELA VIVIANA'; $user->email = 'odonto216@gmail.com'; $user->password = bcrypt('12345678'); $user->save();
        // $user = new User; $user->id = '217'; $user->name = 'MARULANDA JUAN SEBASTIAN'; $user->email = 'odonto217@gmail.com'; $user->password = bcrypt('12345678'); $user->save();
        // $user = new User; $user->id = '218'; $user->name = 'CARRILLO BEATRIZ EUGENIA'; $user->email = 'odonto218@gmail.com'; $user->password = bcrypt('12345678'); $user->save();
        // $user = new User; $user->id = '219'; $user->name = 'RAMIREZ MARITZA'; $user->email = 'odonto219@gmail.com'; $user->password = bcrypt('12345678'); $user->save();
        // $user = new User; $user->id = '228'; $user->name = 'NARVAEZ VIVIANA'; $user->email = 'odonto228@gmail.com'; $user->password = bcrypt('12345678'); $user->save();
        // $user = new User; $user->id = '221'; $user->name = 'MORAN EDER FABIAN'; $user->email = 'odonto221@gmail.com'; $user->password = bcrypt('12345678'); $user->save();
        // $user = new User; $user->id = '222'; $user->name = 'LOPEZ VICTOR'; $user->email = 'odonto222@gmail.com'; $user->password = bcrypt('12345678'); $user->save();
        // $user = new User; $user->id = '223'; $user->name = 'SILVA RUBY'; $user->email = 'odonto223@gmail.com'; $user->password = bcrypt('12345678'); $user->save();
        // $user = new User; $user->id = '224'; $user->name = 'ARISTIZABAL YENNITH'; $user->email = 'odonto224@gmail.com'; $user->password = bcrypt('12345678'); $user->save();
        // $user = new User; $user->id = '225'; $user->name = 'RODRIGUEZ BEATRIZ'; $user->email = 'odonto225@gmail.com'; $user->password = bcrypt('12345678'); $user->save();
        // $user = new User; $user->id = '226'; $user->name = 'ALDANA JARAMILLO LUISA FERNANDA'; $user->email = 'odonto226@gmail.com'; $user->password = bcrypt('12345678'); $user->save();
        // $user = new User; $user->id = '227'; $user->name = 'ACOSTA MAXIMO'; $user->email = 'odonto227@gmail.com'; $user->password = bcrypt('12345678'); $user->save();
        // $user = new User; $user->id = '229'; $user->name = 'DIAZ YESSICA'; $user->email = 'odonto229@gmail.com'; $user->password = bcrypt('12345678'); $user->save();
        // $user = new User; $user->id = '230'; $user->name = 'VICTORIA JAVIER'; $user->email = 'odonto230@gmail.com'; $user->password = bcrypt('12345678'); $user->save();
        // $user = new User; $user->id = '231'; $user->name = 'MARIN JUAN MANUEL'; $user->email = 'odonto231@gmail.com'; $user->password = bcrypt('12345678'); $user->save();
        // $user = new User; $user->id = '232'; $user->name = 'BEDOYA RICARDO'; $user->email = 'odonto232@gmail.com'; $user->password = bcrypt('12345678'); $user->save();
        // $user = new User; $user->id = '233'; $user->name = 'PAREDES VANESSA'; $user->email = 'odonto233@gmail.com'; $user->password = bcrypt('12345678'); $user->save();
        // $user = new User; $user->id = '234'; $user->name = 'PAREDES RAFAEL'; $user->email = 'odonto234@gmail.com'; $user->password = bcrypt('12345678'); $user->save();
        // $user = new User; $user->id = '235'; $user->name = 'DIAZ OBDULIO'; $user->email = 'odonto235@gmail.com'; $user->password = bcrypt('12345678'); $user->save();
        // $user = new User; $user->id = '236'; $user->name = 'TORO JULIO CESAR'; $user->email = 'odonto236@gmail.com'; $user->password = bcrypt('12345678'); $user->save();
        // $user = new User; $user->id = '237'; $user->name = 'AGUALIMPIA DIANA ISABEL'; $user->email = 'odonto237@gmail.com'; $user->password = bcrypt('12345678'); $user->save();
        // $user = new User; $user->id = '238'; $user->name = 'TAYLOR EVELYN FAWISA'; $user->email = 'odonto238@gmail.com'; $user->password = bcrypt('12345678'); $user->save();
        // $user = new User; $user->id = '239'; $user->name = 'ARANA MARTHA LUCIA'; $user->email = 'odonto239@gmail.com'; $user->password = bcrypt('12345678'); $user->save();
        // $user = new User; $user->id = '240'; $user->name = 'CATAÃ‘O HEBERTH'; $user->email = 'odonto240@gmail.com'; $user->password = bcrypt('12345678'); $user->save();
        // $user = new User; $user->id = '241'; $user->name = 'VARON JAIME HERNAN'; $user->email = 'odonto241@gmail.com'; $user->password = bcrypt('12345678'); $user->save();
        // $user = new User; $user->id = '242'; $user->name = 'VACCA FEDERICO ALEJANDRO'; $user->email = 'odonto242@gmail.com'; $user->password = bcrypt('12345678'); $user->save();
        // $user = new User; $user->id = '243'; $user->name = 'CAICEDO CARLOS'; $user->email = 'odonto243@gmail.com'; $user->password = bcrypt('12345678'); $user->save();
        // $user = new User; $user->id = '244'; $user->name = 'MOISES ALEGRIA'; $user->email = 'odonto244@gmail.com'; $user->password = bcrypt('12345678'); $user->save();
        // $user = new User; $user->id = '220'; $user->name = 'URBANO LOZANO SANDRA PAOLA'; $user->email = 'odonto220@gmail.com'; $user->password = bcrypt('12345678'); $user->save();
        // $user = new User; $user->id = '246'; $user->name = 'MAYA SAYDA MARITZA'; $user->email = 'odonto246@gmail.com'; $user->password = bcrypt('12345678'); $user->save();
        // $user = new User; $user->id = '247'; $user->name = 'ALUMA MARIA LOURDES'; $user->email = 'odonto247@gmail.com'; $user->password = bcrypt('12345678'); $user->save();
        // $user = new User; $user->id = '248'; $user->name = 'VELA CLEMENCIA'; $user->email = 'odonto248@gmail.com'; $user->password = bcrypt('12345678'); $user->save();
        // $user = new User; $user->id = '249'; $user->name = 'ARIAS MAURICIO'; $user->email = 'odonto249@gmail.com'; $user->password = bcrypt('12345678'); $user->save();
        // $user = new User; $user->id = '250'; $user->name = 'POTES MARIA CAMILA'; $user->email = 'odonto250@gmail.com'; $user->password = bcrypt('12345678'); $user->save();
        // $user = new User; $user->id = '251'; $user->name = 'CATAÃ‘O VELASQUEZ LAURA CATALINA'; $user->email = 'odonto251@gmail.com'; $user->password = bcrypt('12345678'); $user->save();
        // $user = new User; $user->id = '252'; $user->name = 'GALLARDO PEREA CARLOS ARTURO'; $user->email = 'odonto252@gmail.com'; $user->password = bcrypt('12345678'); $user->save();
        // $user = new User; $user->id = '253'; $user->name = 'TAMAYO VICTORIA'; $user->email = 'odonto253@gmail.com'; $user->password = bcrypt('12345678'); $user->save();
        // $user = new User; $user->id = '254'; $user->name = 'GALINDO MARCELA'; $user->email = 'odonto254@gmail.com'; $user->password = bcrypt('12345678'); $user->save();
        // $user = new User; $user->id = '255'; $user->name = 'CARDOZO MARIA ALEJANDRA'; $user->email = 'odonto255@gmail.com'; $user->password = bcrypt('12345678'); $user->save();
        // $user = new User; $user->id = '256'; $user->name = 'TRIVIÃ‘O JORGE ALBERTO'; $user->email = 'odonto256@gmail.com'; $user->password = bcrypt('12345678'); $user->save();
        // $user = new User; $user->id = '257'; $user->name = 'PEREZ VICTORIA EUGENIA'; $user->email = 'odonto257@gmail.com'; $user->password = bcrypt('12345678'); $user->save();
        // $user = new User; $user->id = '258'; $user->name = 'ARISTIZABAL JAVIER ANDRES'; $user->email = 'odonto258@gmail.com'; $user->password = bcrypt('12345678'); $user->save();
        // $user = new User; $user->id = '259'; $user->name = 'BRACKETS ORAL'; $user->email = 'odonto259@gmail.com'; $user->password = bcrypt('12345678'); $user->save();
        // $user = new User; $user->id = '260'; $user->name = 'LUCUMI ANGELA'; $user->email = 'odonto260@gmail.com'; $user->password = bcrypt('12345678'); $user->save();
        // $user = new User; $user->id = '261'; $user->name = 'CARDENAS AMILKAR'; $user->email = 'odonto261@gmail.com'; $user->password = bcrypt('12345678'); $user->save();
        // $user = new User; $user->id = '262'; $user->name = 'SANCHEZ MARIA DEL SOCORRO'; $user->email = 'odonto262@gmail.com'; $user->password = bcrypt('12345678'); $user->save();
        // $user = new User; $user->id = '263'; $user->name = 'CASTAÃ‘O LUCY'; $user->email = 'odonto263@gmail.com'; $user->password = bcrypt('12345678'); $user->save();
        // $user = new User; $user->id = '264'; $user->name = 'GARCIA MARIA OLIVIA'; $user->email = 'odonto264@gmail.com'; $user->password = bcrypt('12345678'); $user->save();
        // $user = new User; $user->id = '265'; $user->name = 'PARRA FERNANDO'; $user->email = 'odonto265@gmail.com'; $user->password = bcrypt('12345678'); $user->save();
        // $user = new User; $user->id = '266'; $user->name = 'VALLEJO ANGELA MARIA'; $user->email = 'odonto266@gmail.com'; $user->password = bcrypt('12345678'); $user->save();
        // $user = new User; $user->id = '267'; $user->name = 'MONTILLO CLARA ELENA'; $user->email = 'odonto267@gmail.com'; $user->password = bcrypt('12345678'); $user->save();
        // $user = new User; $user->id = '268'; $user->name = 'MADRID ALEJANDRA'; $user->email = 'odonto268@gmail.com'; $user->password = bcrypt('12345678'); $user->save();
        // $user = new User; $user->id = '269'; $user->name = 'DAVILA OLGA LUCIA'; $user->email = 'odonto269@gmail.com'; $user->password = bcrypt('12345678'); $user->save();
        // $user = new User; $user->id = '270'; $user->name = 'GODOY LUIS FERNANDO'; $user->email = 'odonto270@gmail.com'; $user->password = bcrypt('12345678'); $user->save();
        // $user = new User; $user->id = '271'; $user->name = 'CORREDOR ANA MILENA'; $user->email = 'odonto271@gmail.com'; $user->password = bcrypt('12345678'); $user->save();
        // $user = new User; $user->id = '272'; $user->name = 'PEREZ GALVEZ SANDRA MARCELA'; $user->email = 'odonto272@gmail.com'; $user->password = bcrypt('12345678'); $user->save();
        // $user = new User; $user->id = '273'; $user->name = 'RIVAS ANDRES MAURICIO'; $user->email = 'odonto273@gmail.com'; $user->password = bcrypt('12345678'); $user->save();
        // $user = new User; $user->id = '274'; $user->name = 'VALDES JULIAN ALBERTO'; $user->email = 'odonto274@gmail.com'; $user->password = bcrypt('12345678'); $user->save();
        // $user = new User; $user->id = '275'; $user->name = 'VASQUEZ DIANA MARIA'; $user->email = 'odonto275@gmail.com'; $user->password = bcrypt('12345678'); $user->save();
        // $user = new User; $user->id = '276'; $user->name = 'SANCHEZ YURI'; $user->email = 'odonto276@gmail.com'; $user->password = bcrypt('12345678'); $user->save();
        // $user = new User; $user->id = '277'; $user->name = 'CASTRILLON WILLIAM'; $user->email = 'odonto277@gmail.com'; $user->password = bcrypt('12345678'); $user->save();
        // $user = new User; $user->id = '278'; $user->name = 'CRUZ PATRICIA'; $user->email = 'odonto278@gmail.com'; $user->password = bcrypt('12345678'); $user->save();
        // $user = new User; $user->id = '280'; $user->name = 'GOMEZ LONDOÃ‘O LUIS HERNAN'; $user->email = 'odonto280@gmail.com'; $user->password = bcrypt('12345678'); $user->save();
        // $user = new User; $user->id = '281'; $user->name = 'BARRAZA ALVARADO DIANA MILENA'; $user->email = 'odonto281@gmail.com'; $user->password = bcrypt('12345678'); $user->save();
        // $user = new User; $user->id = '282'; $user->name = 'VALENCIA ERIKA'; $user->email = 'odonto282@gmail.com'; $user->password = bcrypt('12345678'); $user->save();
        // $user = new User; $user->id = '279'; $user->name = 'CABALLERO KATHERINE'; $user->email = 'odonto279@gmail.com'; $user->password = bcrypt('12345678'); $user->save();
        // $user = new User; $user->id = '2'; $user->name = 'VILLEGAS FRANCISCO'; $user->email = 'odonto2@gmail.com'; $user->password = bcrypt('12345678'); $user->save();
        // $user = new User; $user->id = '3'; $user->name = 'LOPEZ JHON JADER'; $user->email = 'odonto3@gmail.com'; $user->password = bcrypt('12345678'); $user->save();
        // $user = new User; $user->id = '5'; $user->name = 'CRUZ ANDRES'; $user->email = 'odonto5@gmail.com'; $user->password = bcrypt('12345678'); $user->save();
        // $user = new User; $user->id = '6'; $user->name = 'BRAVO MEJIA ANDRES'; $user->email = 'odonto6@gmail.com'; $user->password = bcrypt('12345678'); $user->save();
        // $user = new User; $user->id = '7'; $user->name = 'ARIAS HENAO JOHANA ISABEL'; $user->email = 'odonto7@gmail.com'; $user->password = bcrypt('12345678'); $user->save();
        // $user = new User; $user->id = '8'; $user->name = 'SERVISALUD IPS'; $user->email = 'odonto8@gmail.com'; $user->password = bcrypt('12345678'); $user->save();
        // $user = new User; $user->id = '9'; $user->name = 'GUZMAN MELKISEDET'; $user->email = 'odonto9@gmail.com'; $user->password = bcrypt('12345678'); $user->save();
        // $user = new User; $user->id = '10'; $user->name = 'SILVA GINNA'; $user->email = 'odonto10@gmail.com'; $user->password = bcrypt('12345678'); $user->save();
        // $user = new User; $user->id = '11'; $user->name = 'VELANDIA MARIA OTILIA'; $user->email = 'odonto11@gmail.com'; $user->password = bcrypt('12345678'); $user->save();
        // $user = new User; $user->id = '12'; $user->name = 'SANCHEZ UREÃ‘A MAURICIO'; $user->email = 'odonto12@gmail.com'; $user->password = bcrypt('12345678'); $user->save();
        // $user = new User; $user->id = '13'; $user->name = 'SALAZAR HENRY'; $user->email = 'odonto13@gmail.com'; $user->password = bcrypt('12345678'); $user->save();
        // $user = new User; $user->id = '14'; $user->name = 'POTES FRANCISCO'; $user->email = 'odonto14@gmail.com'; $user->password = bcrypt('12345678'); $user->save();
        // $user = new User; $user->id = '15'; $user->name = 'CASTILLO RICO YOLANDA'; $user->email = 'odonto15@gmail.com'; $user->password = bcrypt('12345678'); $user->save();
        // $user = new User; $user->id = '16'; $user->name = 'PEÃ‘ARANDA EDNA VICTORIA'; $user->email = 'odonto16@gmail.com'; $user->password = bcrypt('12345678'); $user->save();
        // $user = new User; $user->id = '18'; $user->name = 'TORO DAVID'; $user->email = 'odonto18@gmail.com'; $user->password = bcrypt('12345678'); $user->save();
        // $user = new User; $user->id = '19'; $user->name = 'CRUZ ANDRES MAURICIO'; $user->email = 'odonto19@gmail.com'; $user->password = bcrypt('12345678'); $user->save();
        // $user = new User; $user->id = '283'; $user->name = 'ROJAS DIEGO'; $user->email = 'odonto283@gmail.com'; $user->password = bcrypt('12345678'); $user->save();
        // $user = new User; $user->id = '284'; $user->name = 'ORTEGON EDGAR AUGUSTO'; $user->email = 'odonto284@gmail.com'; $user->password = bcrypt('12345678'); $user->save();
        // $user = new User; $user->id = '285'; $user->name = 'RODRIGUEZ ANGELICA'; $user->email = 'odonto285@gmail.com'; $user->password = bcrypt('12345678'); $user->save();
        // $user = new User; $user->id = '286'; $user->name = 'LONDOÃ‘O MARIA ELENA'; $user->email = 'odonto286@gmail.com'; $user->password = bcrypt('12345678'); $user->save();
        // $user = new User; $user->id = '287'; $user->name = 'BOTERO MONICA'; $user->email = 'odonto287@gmail.com'; $user->password = bcrypt('12345678'); $user->save();
        // $user = new User; $user->id = '288'; $user->name = 'BOTERO YANETH'; $user->email = 'odonto288@gmail.com'; $user->password = bcrypt('12345678'); $user->save();
        // $user = new User; $user->id = '289'; $user->name = 'CORDOBA LINA'; $user->email = 'odonto289@gmail.com'; $user->password = bcrypt('12345678'); $user->save();
        // $user = new User; $user->id = '290'; $user->name = 'MURIEL SONIA ASTRID'; $user->email = 'odonto290@gmail.com'; $user->password = bcrypt('12345678'); $user->save();
        // $user = new User; $user->id = '291'; $user->name = 'OVALLE CLAUDIA'; $user->email = 'odonto291@gmail.com'; $user->password = bcrypt('12345678'); $user->save();
        // $user = new User; $user->id = '292'; $user->name = 'RAMIREZ JUAN CARLOS'; $user->email = 'odonto292@gmail.com'; $user->password = bcrypt('12345678'); $user->save();
        // $user = new User; $user->id = '293'; $user->name = 'ALBA LEON DINACELLY'; $user->email = 'odonto293@gmail.com'; $user->password = bcrypt('12345678'); $user->save();
        // $user = new User; $user->id = '296'; $user->name = 'GONZALEZ MARIA PILAR'; $user->email = 'odonto296@gmail.com'; $user->password = bcrypt('12345678'); $user->save();
        // $user = new User; $user->id = '294'; $user->name = 'BUSTOS GIOVANNY'; $user->email = 'odonto294@gmail.com'; $user->password = bcrypt('12345678'); $user->save();
        // $user = new User; $user->id = '295'; $user->name = 'MUÃ‘OZ MIGUEL ANGEL'; $user->email = 'odonto295@gmail.com'; $user->password = bcrypt('12345678'); $user->save();
        // $user = new User; $user->id = '297'; $user->name = 'OSPINA LUIS HERNESTO'; $user->email = 'odonto297@gmail.com'; $user->password = bcrypt('12345678'); $user->save();
        // $user = new User; $user->id = '298'; $user->name = 'ARROYAVE HAROLD'; $user->email = 'odonto298@gmail.com'; $user->password = bcrypt('12345678'); $user->save();
        // $user = new User; $user->id = '299'; $user->name = 'CRUZ XIMENA'; $user->email = 'odonto299@gmail.com'; $user->password = bcrypt('12345678'); $user->save();
        // $user = new User; $user->id = '301'; $user->name = 'CRUZ ANGELICA'; $user->email = 'odonto301@gmail.com'; $user->password = bcrypt('12345678'); $user->save();
        // $user = new User; $user->id = '302'; $user->name = 'ZUÃ‘IGA BEATRIZ EUGENIA'; $user->email = 'odonto302@gmail.com'; $user->password = bcrypt('12345678'); $user->save();
        // $user = new User; $user->id = '300'; $user->name = 'DUQUE LILIAN'; $user->email = 'odonto300@gmail.com'; $user->password = bcrypt('12345678'); $user->save();
        // $user = new User; $user->id = '4'; $user->name = 'SUAREZ IVAN'; $user->email = 'odonto4@gmail.com'; $user->password = bcrypt('12345678'); $user->save();
        // $user = new User; $user->id = '21'; $user->name = 'ALZATE UMAÃ‘A PAULA TATIANA'; $user->email = 'odonto21@gmail.com'; $user->password = bcrypt('12345678'); $user->save();
        // $user = new User; $user->id = '22'; $user->name = 'TENORIO GOMEZ LUZ AMPARO'; $user->email = 'odonto22@gmail.com'; $user->password = bcrypt('12345678'); $user->save();
        // $user = new User; $user->id = '23'; $user->name = 'YELA CARLOS'; $user->email = 'odonto23@gmail.com'; $user->password = bcrypt('12345678'); $user->save();
        // $user = new User; $user->id = '24'; $user->name = 'HENAO DIANA MARCELA'; $user->email = 'odonto24@gmail.com'; $user->password = bcrypt('12345678'); $user->save();
        // $user = new User; $user->id = '25'; $user->name = 'ASSIA DAYANI'; $user->email = 'odonto25@gmail.com'; $user->password = bcrypt('12345678'); $user->save();
        // $user = new User; $user->id = '26'; $user->name = 'OSPINA DIANA CAROLINA'; $user->email = 'odonto26@gmail.com'; $user->password = bcrypt('12345678'); $user->save();
        // $user = new User; $user->id = '27'; $user->name = 'MENA CARLOS'; $user->email = 'odonto27@gmail.com'; $user->password = bcrypt('12345678'); $user->save();
        // $user = new User; $user->id = '28'; $user->name = 'GIRALDO GERMAN'; $user->email = 'odonto28@gmail.com'; $user->password = bcrypt('12345678'); $user->save();
        // $user = new User; $user->id = '29'; $user->name = 'GALVEZ CAMILO'; $user->email = 'odonto29@gmail.com'; $user->password = bcrypt('12345678'); $user->save();
        // $user = new User; $user->id = '30'; $user->name = 'ESPINOZA CARLOS'; $user->email = 'odonto30@gmail.com'; $user->password = bcrypt('12345678'); $user->save();
        // $user = new User; $user->id = '31'; $user->name = 'GALVEZ CARLOS'; $user->email = 'odonto31@gmail.com'; $user->password = bcrypt('12345678'); $user->save();
        // $user = new User; $user->id = '32'; $user->name = 'RODRIGUEZ CAROLINA'; $user->email = 'odonto32@gmail.com'; $user->password = bcrypt('12345678'); $user->save();
        // $user = new User; $user->id = '33'; $user->name = 'RODRIGUEZ CESAR'; $user->email = 'odonto33@gmail.com'; $user->password = bcrypt('12345678'); $user->save();
        // $user = new User; $user->id = '34'; $user->name = 'SANCHEZ CLAUDIA'; $user->email = 'odonto34@gmail.com'; $user->password = bcrypt('12345678'); $user->save();
        // $user = new User; $user->id = '35'; $user->name = 'NOVOA DIEGO'; $user->email = 'odonto35@gmail.com'; $user->password = bcrypt('12345678'); $user->save();
        // $user = new User; $user->id = '36'; $user->name = 'VASQUEZ INGRID'; $user->email = 'odonto36@gmail.com'; $user->password = bcrypt('12345678'); $user->save();
        // $user = new User; $user->id = '38'; $user->name = 'SERRANO LILIANA'; $user->email = 'odonto38@gmail.com'; $user->password = bcrypt('12345678'); $user->save();
        // $user = new User; $user->id = '39'; $user->name = 'TELLO LINA MARIA'; $user->email = 'odonto39@gmail.com'; $user->password = bcrypt('12345678'); $user->save();
        // $user = new User; $user->id = '40'; $user->name = 'DIAZ ROGER'; $user->email = 'odonto40@gmail.com'; $user->password = bcrypt('12345678'); $user->save();
        // $user = new User; $user->id = '41'; $user->name = 'AVELLANEDA SILVIA'; $user->email = 'odonto41@gmail.com'; $user->password = bcrypt('12345678'); $user->save();
        // $user = new User; $user->id = '42'; $user->name = 'RAMIREZ VALENTINA'; $user->email = 'odonto42@gmail.com'; $user->password = bcrypt('12345678'); $user->save();
        // $user = new User; $user->id = '43'; $user->name = 'MARTINEZ VICTOR'; $user->email = 'odonto43@gmail.com'; $user->password = bcrypt('12345678'); $user->save();
        // $user = new User; $user->id = '44'; $user->name = 'VILLEGAS LUIS ALBERTO'; $user->email = 'odonto44@gmail.com'; $user->password = bcrypt('12345678'); $user->save();
        // $user = new User; $user->id = '45'; $user->name = 'AGUADO BETTY'; $user->email = 'odonto45@gmail.com'; $user->password = bcrypt('12345678'); $user->save();
        // $user = new User; $user->id = '46'; $user->name = 'MORA GLORIA AMPARO'; $user->email = 'odonto46@gmail.com'; $user->password = bcrypt('12345678'); $user->save();
        // $user = new User; $user->id = '47'; $user->name = 'BEJARANO RAMSES EVELIO'; $user->email = 'odonto47@gmail.com'; $user->password = bcrypt('12345678'); $user->save();
        // $user = new User; $user->id = '48'; $user->name = 'ECHEVERRIA PATRICIO'; $user->email = 'odonto48@gmail.com'; $user->password = bcrypt('12345678'); $user->save();
        // $user = new User; $user->id = '49'; $user->name = 'ESCOBAR MARIA TERESA'; $user->email = 'odonto49@gmail.com'; $user->password = bcrypt('12345678'); $user->save();
        // $user = new User; $user->id = '50'; $user->name = 'MONTOYA ANA RITA'; $user->email = 'odonto50@gmail.com'; $user->password = bcrypt('12345678'); $user->save();
        // $user = new User; $user->id = '51'; $user->name = 'SALGADO ALEJANDRO'; $user->email = 'odonto51@gmail.com'; $user->password = bcrypt('12345678'); $user->save();
        // $user = new User; $user->id = '53'; $user->name = 'GARCIA ANDRES'; $user->email = 'odonto53@gmail.com'; $user->password = bcrypt('12345678'); $user->save();
        // $user = new User; $user->id = '55'; $user->name = 'PULGARIN DANIEL'; $user->email = 'odonto55@gmail.com'; $user->password = bcrypt('12345678'); $user->save();
        // $user = new User; $user->id = '37'; $user->name = 'VALBUENA JOSE'; $user->email = 'odonto37@gmail.com'; $user->password = bcrypt('12345678'); $user->save();
        // $user = new User; $user->id = '56'; $user->name = 'GARCIA DIANA MARIA'; $user->email = 'odonto56@gmail.com'; $user->password = bcrypt('12345678'); $user->save();
        // $user = new User; $user->id = '57'; $user->name = 'REVOLLO DOMINIQUE'; $user->email = 'odonto57@gmail.com'; $user->password = bcrypt('12345678'); $user->save();
        // $user = new User; $user->id = '58'; $user->name = 'HERRERA DORA MILENA'; $user->email = 'odonto58@gmail.com'; $user->password = bcrypt('12345678'); $user->save();
        // $user = new User; $user->id = '54'; $user->name = 'ZULUAGA CATALINA'; $user->email = 'odonto54@gmail.com'; $user->password = bcrypt('12345678'); $user->save();
        // $user = new User; $user->id = '60'; $user->name = 'RADA FERNANDO'; $user->email = 'odonto60@gmail.com'; $user->password = bcrypt('12345678'); $user->save();
        // $user = new User; $user->id = '61'; $user->name = 'GUTIERREZ GERARDO'; $user->email = 'odonto61@gmail.com'; $user->password = bcrypt('12345678'); $user->save();
        // $user = new User; $user->id = '63'; $user->name = 'CORDOBA MARIA ALEJANDRA'; $user->email = 'odonto63@gmail.com'; $user->password = bcrypt('12345678'); $user->save();
        // $user = new User; $user->id = '64'; $user->name = 'RINCON MAURICIO'; $user->email = 'odonto64@gmail.com'; $user->password = bcrypt('12345678'); $user->save();
        // $user = new User; $user->id = '65'; $user->name = 'RAMIREZ MONICA'; $user->email = 'odonto65@gmail.com'; $user->password = bcrypt('12345678'); $user->save();
        // $user = new User; $user->id = '66'; $user->name = 'ARANGO PAOLA A.'; $user->email = 'odonto66@gmail.com'; $user->password = bcrypt('12345678'); $user->save();
        // $user = new User; $user->id = '67'; $user->name = 'KAMAL RASSUL ALDIB'; $user->email = 'odonto67@gmail.com'; $user->password = bcrypt('12345678'); $user->save();
        // $user = new User; $user->id = '68'; $user->name = 'PINZON SANDRA'; $user->email = 'odonto68@gmail.com'; $user->password = bcrypt('12345678'); $user->save();
        // $user = new User; $user->id = '69'; $user->name = 'ALVAREZ SANDRA'; $user->email = 'odonto69@gmail.com'; $user->password = bcrypt('12345678'); $user->save();
        // $user = new User; $user->id = '71'; $user->name = 'CASTILLO YOLANDA'; $user->email = 'odonto71@gmail.com'; $user->password = bcrypt('12345678'); $user->save();
        // $user = new User; $user->id = '70'; $user->name = 'MARULANDA VIVIAN'; $user->email = 'odonto70@gmail.com'; $user->password = bcrypt('12345678'); $user->save();
        // $user = new User; $user->id = '72'; $user->name = 'HERRERA NATALIA'; $user->email = 'odonto72@gmail.com'; $user->password = bcrypt('12345678'); $user->save();
        // $user = new User; $user->id = '73'; $user->name = 'GIRON ROSEMBERG'; $user->email = 'odonto73@gmail.com'; $user->password = bcrypt('12345678'); $user->save();
        // $user = new User; $user->id = '74'; $user->name = 'SILVA JUNIOR'; $user->email = 'odonto74@gmail.com'; $user->password = bcrypt('12345678'); $user->save();
        // $user = new User; $user->id = '76'; $user->name = 'BUENO MAURICIO'; $user->email = 'odonto76@gmail.com'; $user->password = bcrypt('12345678'); $user->save();
        // $user = new User; $user->id = '75'; $user->name = 'CASTRILLON BLAYBIR'; $user->email = 'odonto75@gmail.com'; $user->password = bcrypt('12345678'); $user->save();
        // $user = new User; $user->id = '77'; $user->name = 'REDONDO PAOLA'; $user->email = 'odonto77@gmail.com'; $user->password = bcrypt('12345678'); $user->save();
        // $user = new User; $user->id = '78'; $user->name = 'LOPEZ GERARDO'; $user->email = 'odonto78@gmail.com'; $user->password = bcrypt('12345678'); $user->save();
        // $user = new User; $user->id = '80'; $user->name = 'GOMEZ ANGELA'; $user->email = 'odonto80@gmail.com'; $user->password = bcrypt('12345678'); $user->save();
        // $user = new User; $user->id = '81'; $user->name = 'PEREZ JERRY'; $user->email = 'odonto81@gmail.com'; $user->password = bcrypt('12345678'); $user->save();
        // $user = new User; $user->id = '82'; $user->name = 'RENGIFO MILENA'; $user->email = 'odonto82@gmail.com'; $user->password = bcrypt('12345678'); $user->save();
        // $user = new User; $user->id = '83'; $user->name = 'SEIYELI MUÃ‘OZ'; $user->email = 'odonto83@gmail.com'; $user->password = bcrypt('12345678'); $user->save();
        // $user = new User; $user->id = '84'; $user->name = 'ALBA ANDRES DAVID'; $user->email = 'odonto84@gmail.com'; $user->password = bcrypt('12345678'); $user->save();
        // $user = new User; $user->id = '85'; $user->name = 'GUERRERO MAURICIO'; $user->email = 'odonto85@gmail.com'; $user->password = bcrypt('12345678'); $user->save();
        // $user = new User; $user->id = '86'; $user->name = 'PUERTA ERIKA'; $user->email = 'odonto86@gmail.com'; $user->password = bcrypt('12345678'); $user->save();
        // $user = new User; $user->id = '87'; $user->name = 'CUENCA YURI'; $user->email = 'odonto87@gmail.com'; $user->password = bcrypt('12345678'); $user->save();
        // $user = new User; $user->id = '88'; $user->name = 'MORALES LUIS GABRIEL'; $user->email = 'odonto88@gmail.com'; $user->password = bcrypt('12345678'); $user->save();
        // $user = new User; $user->id = '89'; $user->name = 'RUEDA JACOBO'; $user->email = 'odonto89@gmail.com'; $user->password = bcrypt('12345678'); $user->save();
        // $user = new User; $user->id = '90'; $user->name = 'ALZATE CATALINA'; $user->email = 'odonto90@gmail.com'; $user->password = bcrypt('12345678'); $user->save();
        // $user = new User; $user->id = '91'; $user->name = 'RIVERA EDINSON'; $user->email = 'odonto91@gmail.com'; $user->password = bcrypt('12345678'); $user->save();
        // $user = new User; $user->id = '92'; $user->name = 'ALVIS MARCELO'; $user->email = 'odonto92@gmail.com'; $user->password = bcrypt('12345678'); $user->save();
        // $user = new User; $user->id = '93'; $user->name = 'DIAZ LUIS ALEJANDRO'; $user->email = 'odonto93@gmail.com'; $user->password = bcrypt('12345678'); $user->save();
        // $user = new User; $user->id = '94'; $user->name = 'VARGAS MARCELA'; $user->email = 'odonto94@gmail.com'; $user->password = bcrypt('12345678'); $user->save();
        // $user = new User; $user->id = '95'; $user->name = 'QUINTERO DIANA'; $user->email = 'odonto95@gmail.com'; $user->password = bcrypt('12345678'); $user->save();
        // $user = new User; $user->id = '96'; $user->name = 'MORALES MARTIZA'; $user->email = 'odonto96@gmail.com'; $user->password = bcrypt('12345678'); $user->save();
        // $user = new User; $user->id = '97'; $user->name = 'DIAZ GLORIA'; $user->email = 'odonto97@gmail.com'; $user->password = bcrypt('12345678'); $user->save();
        // $user = new User; $user->id = '79'; $user->name = 'HINCAPIE GINA'; $user->email = 'odonto79@gmail.com'; $user->password = bcrypt('12345678'); $user->save();
        // $user = new User; $user->id = '105'; $user->name = 'ESPERANZA  GOMEZ                                  '; $user->email = 'odonto105@gmail.com'; $user->password = bcrypt('12345678'); $user->save();
        // $user = new User; $user->id = '999'; $user->name = 'GENERICO'; $user->email = 'odonto999@gmail.com'; $user->password = bcrypt('12345678'); $user->save();
        // $user = new User; $user->id = '306'; $user->name = 'ORTOESTETICA'; $user->email = 'odonto306@gmail.com'; $user->password = bcrypt('12345678'); $user->save();
        // $user = new User; $user->id = '99'; $user->name = 'GARCIA CESAR'; $user->email = 'odonto99@gmail.com'; $user->password = bcrypt('12345678'); $user->save();
        // $user = new User; $user->id = '100'; $user->name = 'GRAJALES OSCAR'; $user->email = 'odonto100@gmail.com'; $user->password = bcrypt('12345678'); $user->save();
        // $user = new User; $user->id = '101'; $user->name = 'GOMEZ OLGA XIMENA'; $user->email = 'odonto101@gmail.com'; $user->password = bcrypt('12345678'); $user->save();
        // $user = new User; $user->id = '102'; $user->name = 'MARIN DANILO'; $user->email = 'odonto102@gmail.com'; $user->password = bcrypt('12345678'); $user->save();
        // $user = new User; $user->id = '103'; $user->name = 'DIAZ CARLOS W.'; $user->email = 'odonto103@gmail.com'; $user->password = bcrypt('12345678'); $user->save();
        // $user = new User; $user->id = '104'; $user->name = 'MARIN LUZ HELENA'; $user->email = 'odonto104@gmail.com'; $user->password = bcrypt('12345678'); $user->save();
        // $user = new User; $user->id = '106'; $user->name = 'SHEIK CLAUDIA XIMENA'; $user->email = 'odonto106@gmail.com'; $user->password = bcrypt('12345678'); $user->save();
        // $user = new User; $user->id = '107'; $user->name = 'CABALLERO OSCAR'; $user->email = 'odonto107@gmail.com'; $user->password = bcrypt('12345678'); $user->save();
        // $user = new User; $user->id = '108'; $user->name = 'DAZA WILLIAM'; $user->email = 'odonto108@gmail.com'; $user->password = bcrypt('12345678'); $user->save();
        // $user = new User; $user->id = '109'; $user->name = 'AVILA CARMEN DELIA'; $user->email = 'odonto109@gmail.com'; $user->password = bcrypt('12345678'); $user->save();
        // $user = new User; $user->id = '110'; $user->name = 'VALDERRAMA ANGELA'; $user->email = 'odonto110@gmail.com'; $user->password = bcrypt('12345678'); $user->save();
        // $user = new User; $user->id = '111'; $user->name = 'BEDOYA LORENA MARIA'; $user->email = 'odonto111@gmail.com'; $user->password = bcrypt('12345678'); $user->save();
        // $user = new User; $user->id = '112'; $user->name = 'MURIEL IVETTE'; $user->email = 'odonto112@gmail.com'; $user->password = bcrypt('12345678'); $user->save();
        // $user = new User; $user->id = '113'; $user->name = 'CASTAÃ‘O MARIA ANTONIA'; $user->email = 'odonto113@gmail.com'; $user->password = bcrypt('12345678'); $user->save();
        // $user = new User; $user->id = '114'; $user->name = 'ESCALANTE ANA'; $user->email = 'odonto114@gmail.com'; $user->password = bcrypt('12345678'); $user->save();
        // $user = new User; $user->id = '115'; $user->name = 'DENTAL CENTRO ESTETICA'; $user->email = 'odonto115@gmail.com'; $user->password = bcrypt('12345678'); $user->save();
        // $user = new User; $user->id = '116'; $user->name = 'MORALES HAROLD'; $user->email = 'odonto116@gmail.com'; $user->password = bcrypt('12345678'); $user->save();
        // $user = new User; $user->id = '117'; $user->name = 'LONDOÃ‘O HARRISON'; $user->email = 'odonto117@gmail.com'; $user->password = bcrypt('12345678'); $user->save();
        // $user = new User; $user->id = '118'; $user->name = 'SANCHEZ MARIA SOCORRO'; $user->email = 'odonto118@gmail.com'; $user->password = bcrypt('12345678'); $user->save();
        // $user = new User; $user->id = '119'; $user->name = 'CAICEO MANUEL'; $user->email = 'odonto119@gmail.com'; $user->password = bcrypt('12345678'); $user->save();
        // $user = new User; $user->id = '121'; $user->name = 'AGREDO FELIPE'; $user->email = 'odonto121@gmail.com'; $user->password = bcrypt('12345678'); $user->save();
        // $user = new User; $user->id = '122'; $user->name = 'MORAN EDER'; $user->email = 'odonto122@gmail.com'; $user->password = bcrypt('12345678'); $user->save();
        // $user = new User; $user->id = '123'; $user->name = 'TORO JOSE EDIDIER'; $user->email = 'odonto123@gmail.com'; $user->password = bcrypt('12345678'); $user->save();
        // $user = new User; $user->id = '124'; $user->name = 'SILVA PASTOR'; $user->email = 'odonto124@gmail.com'; $user->password = bcrypt('12345678'); $user->save();
        // $user = new User; $user->id = '125'; $user->name = 'CHACON ALVARO'; $user->email = 'odonto125@gmail.com'; $user->password = bcrypt('12345678'); $user->save();
        // $user = new User; $user->id = '126'; $user->name = 'ARBOLEDA JORGE HERNAN'; $user->email = 'odonto126@gmail.com'; $user->password = bcrypt('12345678'); $user->save();
        // $user = new User; $user->id = '127'; $user->name = 'RAMIREZ VICTOR HUGO'; $user->email = 'odonto127@gmail.com'; $user->password = bcrypt('12345678'); $user->save();
        // $user = new User; $user->id = '128'; $user->name = 'AVEIGA TONY'; $user->email = 'odonto128@gmail.com'; $user->password = bcrypt('12345678'); $user->save();
        // $user = new User; $user->id = '129'; $user->name = 'VALENCIA LEONOR'; $user->email = 'odonto129@gmail.com'; $user->password = bcrypt('12345678'); $user->save();
        // $user = new User; $user->id = '130'; $user->name = 'GUTIERREZ GERARDO'; $user->email = 'odonto130@gmail.com'; $user->password = bcrypt('12345678'); $user->save();
        // $user = new User; $user->id = '303'; $user->name = 'MORALES ARNOBIO'; $user->email = 'odonto303@gmail.com'; $user->password = bcrypt('12345678'); $user->save();
        // $user = new User; $user->id = '304'; $user->name = 'RAMOS JUAN DAVID'; $user->email = 'odonto304@gmail.com'; $user->password = bcrypt('12345678'); $user->save();
        // $user = new User; $user->id = '305'; $user->name = 'ESCOLANTE ANA LUCIA'; $user->email = 'odonto305@gmail.com'; $user->password = bcrypt('12345678'); $user->save();
        // $user = new User; $user->id = '307'; $user->name = 'OCAMPO MILENA'; $user->email = 'odonto307@gmail.com'; $user->password = bcrypt('12345678'); $user->save();
        // $user = new User; $user->id = '308'; $user->name = 'GOMEZ MARIA DEL PILAR'; $user->email = 'odonto308@gmail.com'; $user->password = bcrypt('12345678'); $user->save();
        // $user = new User; $user->id = '309'; $user->name = 'OSORIO JUAN CARLOS'; $user->email = 'odonto309@gmail.com'; $user->password = bcrypt('12345678'); $user->save();
        // $user = new User; $user->id = '317'; $user->name = 'CLINICENTER'; $user->email = 'odonto317@gmail.com'; $user->password = bcrypt('12345678'); $user->save();
        // $user = new User; $user->id = '359'; $user->name = 'SALAZAR DIEGO'; $user->email = 'odonto359@gmail.com'; $user->password = bcrypt('12345678'); $user->save();
        // $user = new User; $user->id = '361'; $user->name = 'PEÃ‘ARANDA HECTOR'; $user->email = 'odonto361@gmail.com'; $user->password = bcrypt('12345678'); $user->save();
        // $user = new User; $user->id = '362'; $user->name = 'LIBREROS JUAN ESTEBAN'; $user->email = 'odonto362@gmail.com'; $user->password = bcrypt('12345678'); $user->save();
        // $user = new User; $user->id = '473'; $user->name = 'VEGA DUBIANA'; $user->email = 'odonto473@gmail.com'; $user->password = bcrypt('12345678'); $user->save();
        // $user = new User; $user->id = '398'; $user->name = 'LOZANO ERIKA'; $user->email = 'odonto398@gmail.com'; $user->password = bcrypt('12345678'); $user->save();
        // $user = new User; $user->id = '52'; $user->name = 'VARELA ALIX MARIA'; $user->email = 'odonto52@gmail.com'; $user->password = bcrypt('12345678'); $user->save();
        // $user = new User; $user->id = '62'; $user->name = 'TRUJILLO JUAN CARLOS'; $user->email = 'odonto62@gmail.com'; $user->password = bcrypt('12345678'); $user->save();
        // $user = new User; $user->id = '120'; $user->name = 'PEÃ‘ARANDA VICTORIA EDNA'; $user->email = 'odonto120@gmail.com'; $user->password = bcrypt('12345678'); $user->save();
        // $user = new User; $user->id = '12358'; $user->name = 'VELANDIA YESENIA'; $user->email = 'odonto12358@gmail.com'; $user->password = bcrypt('12345678'); $user->save();
        // $user = new User; $user->id = '1254'; $user->name = 'SOTO DUQUE CLAUDIA JULIANA'; $user->email = 'odonto1254@gmail.com'; $user->password = bcrypt('12345678'); $user->save();
        // $user = new User; $user->id = '1256'; $user->name = 'SILVA JOSE MANUEL'; $user->email = 'odonto1256@gmail.com'; $user->password = bcrypt('12345678'); $user->save();
        // $user = new User; $user->id = '1259'; $user->name = 'BARRERA ADOLFO'; $user->email = 'odonto1259@gmail.com'; $user->password = bcrypt('12345678'); $user->save();
        // $user = new User; $user->id = '1288'; $user->name = 'MUÃ‘OZ MARIA ALEJANDRA'; $user->email = 'odonto1288@gmail.com'; $user->password = bcrypt('12345678'); $user->save();
        // $user = new User; $user->id = '1458'; $user->name = 'TRUJILLO ADRIANA'; $user->email = 'odonto1458@gmail.com'; $user->password = bcrypt('12345678'); $user->save();
        // $user = new User; $user->id = '169'; $user->name = 'CAMPOS PEÃ‘A ANDRES'; $user->email = 'odonto169@gmail.com'; $user->password = bcrypt('12345678'); $user->save();
        // $user = new User; $user->id = '312'; $user->name = 'BERNAL ANGELICA'; $user->email = 'odonto312@gmail.com'; $user->password = bcrypt('12345678'); $user->save();
        // $user = new User; $user->id = '313'; $user->name = 'SANABRIA H JAIRO'; $user->email = 'odonto313@gmail.com'; $user->password = bcrypt('12345678'); $user->save();
        // $user = new User; $user->id = '314'; $user->name = 'GALLEGO JUAN'; $user->email = 'odonto314@gmail.com'; $user->password = bcrypt('12345678'); $user->save();
        // $user = new User; $user->id = '315'; $user->name = 'DIUZA LORENA'; $user->email = 'odonto315@gmail.com'; $user->password = bcrypt('12345678'); $user->save();
        // $user = new User; $user->id = '318'; $user->name = 'GARCIA MURILLO JHON JAIRO'; $user->email = 'odonto318@gmail.com'; $user->password = bcrypt('12345678'); $user->save();
        // $user = new User; $user->id = '316'; $user->name = 'ALAYA JORGE ALBERTO'; $user->email = 'odonto316@gmail.com'; $user->password = bcrypt('12345678'); $user->save();
        // $user = new User; $user->id = '319'; $user->name = 'VILLA GARCIA FERNANDO'; $user->email = 'odonto319@gmail.com'; $user->password = bcrypt('12345678'); $user->save();
        // $user = new User; $user->id = '320'; $user->name = 'CORREA DELIA MARIA'; $user->email = 'odonto320@gmail.com'; $user->password = bcrypt('12345678'); $user->save();
        // $user = new User; $user->id = '321'; $user->name = 'GONZALEZ ISABEL C'; $user->email = 'odonto321@gmail.com'; $user->password = bcrypt('12345678'); $user->save();
        // $user = new User; $user->id = '322'; $user->name = 'VIRGEN ANDRES MAURICIO'; $user->email = 'odonto322@gmail.com'; $user->password = bcrypt('12345678'); $user->save();
        // $user = new User; $user->id = '325'; $user->name = 'AYALA YENNY'; $user->email = 'odonto325@gmail.com'; $user->password = bcrypt('12345678'); $user->save();
        // $user = new User; $user->id = '326'; $user->name = 'MARTINEZ MARIO'; $user->email = 'odonto326@gmail.com'; $user->password = bcrypt('12345678'); $user->save();
        // $user = new User; $user->id = '339'; $user->name = 'GUERRERO JUAN FELIPE'; $user->email = 'odonto339@gmail.com'; $user->password = bcrypt('12345678'); $user->save();
        // $user = new User; $user->id = '356'; $user->name = 'MARIN LUIS A'; $user->email = 'odonto356@gmail.com'; $user->password = bcrypt('12345678'); $user->save();
        // $user = new User; $user->id = '357'; $user->name = 'HURTADO FREDDY'; $user->email = 'odonto357@gmail.com'; $user->password = bcrypt('12345678'); $user->save();
        // $user = new User; $user->id = '358'; $user->name = 'MAYA ALEJANDRO'; $user->email = 'odonto358@gmail.com'; $user->password = bcrypt('12345678'); $user->save();
        // $user = new User; $user->id = '360'; $user->name = 'POSADA CESAR'; $user->email = 'odonto360@gmail.com'; $user->password = bcrypt('12345678'); $user->save();
        // $user = new User; $user->id = '396'; $user->name = 'CRISTANCHO YULIETH'; $user->email = 'odonto396@gmail.com'; $user->password = bcrypt('12345678'); $user->save();
        // $user = new User; $user->id = '456'; $user->name = 'HOYOS JUAN CAMILO'; $user->email = 'odonto456@gmail.com'; $user->password = bcrypt('12345678'); $user->save();
        // $user = new User; $user->id = '4569'; $user->name = 'ALVAREZ VICTORIA NATALIA'; $user->email = 'odonto4569@gmail.com'; $user->password = bcrypt('12345678'); $user->save();
        // $user = new User; $user->id = '458'; $user->name = 'SARRIA HERRERA VICTORIA EUGENIA'; $user->email = 'odonto458@gmail.com'; $user->password = bcrypt('12345678'); $user->save();
        // $user = new User; $user->id = '466'; $user->name = 'CALINO ALEJANDRA'; $user->email = 'odonto466@gmail.com'; $user->password = bcrypt('12345678'); $user->save();
        // $user = new User; $user->id = '52236'; $user->name = 'CASTILLO MARIA JOSE'; $user->email = 'odonto52236@gmail.com'; $user->password = bcrypt('12345678'); $user->save();
        // $user = new User; $user->id = '745'; $user->name = 'MAZUERA LUZ MARY'; $user->email = 'odonto745@gmail.com'; $user->password = bcrypt('12345678'); $user->save();
        // $user = new User; $user->id = '9657'; $user->name = 'VARGAS ALEX FERNANDO'; $user->email = 'odonto9657@gmail.com'; $user->password = bcrypt('12345678'); $user->save();
        // $user = new User; $user->id = '369'; $user->name = 'NATURAL SMILE'; $user->email = 'odonto369@gmail.com'; $user->password = bcrypt('12345678'); $user->save();
        // $user = new User; $user->id = '485'; $user->name = 'HURTADO FREDDY'; $user->email = 'odonto485@gmail.com'; $user->password = bcrypt('12345678'); $user->save();
        // $user = new User; $user->id = '468'; $user->name = 'ROJAS SARA'; $user->email = 'odonto468@gmail.com'; $user->password = bcrypt('12345678'); $user->save();
        // $user = new User; $user->id = '487'; $user->name = 'BUENAÃ‘O L. LUCY STELLA'; $user->email = 'odonto487@gmail.com'; $user->password = bcrypt('12345678'); $user->save();
        // $user = new User; $user->id = '489'; $user->name = 'MOLINA ANGELY'; $user->email = 'odonto489@gmail.com'; $user->password = bcrypt('12345678'); $user->save();
        // $user = new User; $user->id = '486'; $user->name = 'GUEVARA TEEJADA CAROLINA'; $user->email = 'odonto486@gmail.com'; $user->password = bcrypt('12345678'); $user->save();
        // $user = new User; $user->id = '854'; $user->name = 'PUERTA ANA'; $user->email = 'odonto854@gmail.com'; $user->password = bcrypt('12345678'); $user->save();
        // $user = new User; $user->id = '488'; $user->name = 'SANCHEZ DIANA'; $user->email = 'odonto488@gmail.com'; $user->password = bcrypt('12345678'); $user->save();
        // $user = new User; $user->id = '569'; $user->name = 'RAMIREZ GIRALDO KATHERINE'; $user->email = 'odonto569@gmail.com'; $user->password = bcrypt('12345678'); $user->save();
        // $user = new User; $user->id = '491'; $user->name = 'ESTUPIÃ‘AN LAURA'; $user->email = 'odonto491@gmail.com'; $user->password = bcrypt('12345678'); $user->save();
        // $user = new User; $user->id = '412'; $user->name = 'PINZON SANDRA MILENA'; $user->email = 'odonto412@gmail.com'; $user->password = bcrypt('12345678'); $user->save();
        // $user = new User; $user->id = '654'; $user->name = 'TORO G CARLOS EDUARDO'; $user->email = 'odonto654@gmail.com'; $user->password = bcrypt('12345678'); $user->save();
        // $user = new User; $user->id = '17'; $user->name = 'LOPEZ LUZ NEYDA'; $user->email = 'odonto17@gmail.com'; $user->password = bcrypt('12345678'); $user->save();
        // $user = new User; $user->id = '20'; $user->name = 'GARCIA NAGDY'; $user->email = 'odonto20@gmail.com'; $user->password = bcrypt('12345678'); $user->save();
        // $user = new User; $user->id = '452'; $user->name = 'OCAMPO DIVA'; $user->email = 'odonto452@gmail.com'; $user->password = bcrypt('12345678'); $user->save();
        // $user = new User; $user->id = '386'; $user->name = 'CARDONA WILLIAM'; $user->email = 'odonto386@gmail.com'; $user->password = bcrypt('12345678'); $user->save();
        // $user = new User; $user->id = '478'; $user->name = 'TAMAYO FERNANDO'; $user->email = 'odonto478@gmail.com'; $user->password = bcrypt('12345678'); $user->save();
        // $user = new User; $user->id = '563'; $user->name = 'RESTREPO V. JUAN CARLOS'; $user->email = 'odonto563@gmail.com'; $user->password = bcrypt('12345678'); $user->save();
        // $user = new User; $user->id = '8521'; $user->name = 'PARRA JENNIFER'; $user->email = 'odonto8521@gmail.com'; $user->password = bcrypt('12345678'); $user->save();
        // $user = new User; $user->id = '856'; $user->name = 'FORERO VICTOR HUGO'; $user->email = 'odonto856@gmail.com'; $user->password = bcrypt('12345678'); $user->save();
        // $user = new User; $user->id = '59'; $user->name = 'VELEZ EVA MARIA'; $user->email = 'odonto59@gmail.com'; $user->password = bcrypt('12345678'); $user->save();
        // $user = new User; $user->id = '98'; $user->name = 'PRIETO SANDRA LUCIA'; $user->email = 'odonto98@gmail.com'; $user->password = bcrypt('12345678'); $user->save();
        // $user = new User; $user->id = '495'; $user->name = 'POSSO ALEJANDRA'; $user->email = 'odonto495@gmail.com'; $user->password = bcrypt('12345678'); $user->save();
        // $user = new User; $user->id = '131'; $user->name = 'ROBLEDO JUAN CARLOS'; $user->email = 'odonto131@gmail.com'; $user->password = bcrypt('12345678'); $user->save();
        // $user = new User; $user->id = '168'; $user->name = 'LEON ELEONORA'; $user->email = 'odonto168@gmail.com'; $user->password = bcrypt('12345678'); $user->save();
        // $user = new User; $user->id = '496'; $user->name = 'SALAZAR KELY'; $user->email = 'odonto496@gmail.com'; $user->password = bcrypt('12345678'); $user->save();
        // $user = new User; $user->id = '207'; $user->name = 'RAMIREZ DIANA KATHERINE'; $user->email = 'odonto207@gmail.com'; $user->password = bcrypt('12345678'); $user->save();
        // $user = new User; $user->id = '245'; $user->name = 'MARMOLEJO EFRAIN'; $user->email = 'odonto245@gmail.com'; $user->password = bcrypt('12345678'); $user->save();
        // $user = new User; $user->id = '450'; $user->name = 'CUASMAYAN MARIA CAMILA'; $user->email = 'odonto450@gmail.com'; $user->password = bcrypt('12345678'); $user->save();
        // $user = new User; $user->id = '345'; $user->name = 'MOLINA LUZ MARIA'; $user->email = 'odonto345@gmail.com'; $user->password = bcrypt('12345678'); $user->save();
        // $user = new User; $user->id = '435'; $user->name = 'OCAMPO YENNY'; $user->email = 'odonto435@gmail.com'; $user->password = bcrypt('12345678'); $user->save();
        // $user = new User; $user->id = '523'; $user->name = 'FRISNEDA A NATALIA'; $user->email = 'odonto523@gmail.com'; $user->password = bcrypt('12345678'); $user->save();
        // $user = new User; $user->id = '658'; $user->name = 'DIAZ OSCAR GUSTAVO'; $user->email = 'odonto658@gmail.com'; $user->password = bcrypt('12345678'); $user->save();
        // $user = new User; $user->id = '8569'; $user->name = 'GARCIA LINA'; $user->email = 'odonto8569@gmail.com'; $user->password = bcrypt('12345678'); $user->save();
        // $user = new User; $user->id = '514'; $user->name = 'MONTOYA V. ANGELA MARIA'; $user->email = 'odonto514@gmail.com'; $user->password = bcrypt('12345678'); $user->save();
        // $user = new User; $user->id = '4541'; $user->name = 'MORALES JUAN DAVID'; $user->email = 'odonto4541@gmail.com'; $user->password = bcrypt('12345678'); $user->save();
        // $user = new User; $user->id = '410'; $user->name = 'SALAZAR MENDEZ BERNARDO JOSE'; $user->email = 'odonto410@gmail.com'; $user->password = bcrypt('12345678'); $user->save();
        // $user = new User; $user->id = '365'; $user->name = 'SISA'; $user->email = 'odonto365@gmail.com'; $user->password = bcrypt('12345678'); $user->save();
        // $user = new User; $user->id = '366'; $user->name = 'ORALCONFORT'; $user->email = 'odonto366@gmail.com'; $user->password = bcrypt('12345678'); $user->save();
        // $user = new User; $user->id = '394'; $user->name = 'MARIA CAMILA ZAPATA GIRALDO'; $user->email = 'odonto394@gmail.com'; $user->password = bcrypt('12345678'); $user->save();
        // $user = new User; $user->id = '385'; $user->name = 'DAVID GOMEZ'; $user->email = 'odonto385@gmail.com'; $user->password = bcrypt('12345678'); $user->save();
        // $user = new User; $user->id = '397'; $user->name = 'VILLEGAS JAVIER'; $user->email = 'odonto397@gmail.com'; $user->password = bcrypt('12345678'); $user->save();
        // $user = new User; $user->id = '368'; $user->name = 'ARROYAVE ALEJANDRO'; $user->email = 'odonto368@gmail.com'; $user->password = bcrypt('12345678'); $user->save();
        // $user = new User; $user->id = '367'; $user->name = 'VALDERRAMA GUSTAVO'; $user->email = 'odonto367@gmail.com'; $user->password = bcrypt('12345678'); $user->save();
        // $user = new User; $user->id = '351'; $user->name = 'SANCHEZ JULIANA'; $user->email = 'odonto351@gmail.com'; $user->password = bcrypt('12345678'); $user->save();
        // $user = new User; $user->id = '352'; $user->name = 'ORTEGA STEPHANY'; $user->email = 'odonto352@gmail.com'; $user->password = bcrypt('12345678'); $user->save();
        // $user = new User; $user->id = '3214'; $user->name = 'AVILES L. ANDRES .E'; $user->email = 'odonto3214@gmail.com'; $user->password = bcrypt('12345678'); $user->save();
        // $user = new User; $user->id = '524'; $user->name = 'VALENCIA MARTINEZ VALERIA'; $user->email = 'odonto524@gmail.com'; $user->password = bcrypt('12345678'); $user->save();
        // $user = new User; $user->id = '586'; $user->name = 'PRISCILA ALVAREZ SANDRA'; $user->email = 'odonto586@gmail.com'; $user->password = bcrypt('12345678'); $user->save();
        // $user = new User; $user->id = '370'; $user->name = 'PALACIOS DIANA'; $user->email = 'odonto370@gmail.com'; $user->password = bcrypt('12345678'); $user->save();
        // $user = new User; $user->id = '392'; $user->name = 'OCAMPO CARLOS'; $user->email = 'odonto392@gmail.com'; $user->password = bcrypt('12345678'); $user->save();
        // $user = new User; $user->id = '374'; $user->name = 'DURAL SONIA'; $user->email = 'odonto374@gmail.com'; $user->password = bcrypt('12345678'); $user->save();
        // $user = new User; $user->id = '348'; $user->name = 'ROJAS ALVARO DAVID'; $user->email = 'odonto348@gmail.com'; $user->password = bcrypt('12345678'); $user->save();
        // $user = new User; $user->id = '337'; $user->name = 'GARCIA YAMILETH'; $user->email = 'odonto337@gmail.com'; $user->password = bcrypt('12345678'); $user->save();
        // $user = new User; $user->id = '463'; $user->name = 'QUINTERO CLAUDIA'; $user->email = 'odonto463@gmail.com'; $user->password = bcrypt('12345678'); $user->save();
        // $user = new User; $user->id = '8745'; $user->name = 'GIRON JHON ALBERT'; $user->email = 'odonto8745@gmail.com'; $user->password = bcrypt('12345678'); $user->save();
        // $user = new User; $user->id = '852'; $user->name = 'RODRIGUEZ VANESA'; $user->email = 'odonto852@gmail.com'; $user->password = bcrypt('12345678'); $user->save();
        // $user = new User; $user->id = '985'; $user->name = 'CRUZ NHORA'; $user->email = 'odonto985@gmail.com'; $user->password = bcrypt('12345678'); $user->save();
        // $user = new User; $user->id = '5821'; $user->name = 'AGUILERA SARRIA JUAN MANUEL'; $user->email = 'odonto5821@gmail.com'; $user->password = bcrypt('12345678'); $user->save();
        // $user = new User; $user->id = '587'; $user->name = 'BETANCUR PAULA'; $user->email = 'odonto587@gmail.com'; $user->password = bcrypt('12345678'); $user->save();
        // $user = new User; $user->id = '847'; $user->name = 'RESTREPO GUSTAVO'; $user->email = 'odonto847@gmail.com'; $user->password = bcrypt('12345678'); $user->save();
        // $user = new User; $user->id = '3893'; $user->name = 'AGUIRRE SANTIAGO'; $user->email = 'odonto3893@gmail.com'; $user->password = bcrypt('12345678'); $user->save();
        // $user = new User; $user->id = '789'; $user->name = 'AGUIRRE ALEJANDRA'; $user->email = 'odonto789@gmail.com'; $user->password = bcrypt('12345678'); $user->save();
        // $user = new User; $user->id = '1354'; $user->name = 'CALZADA NESTOR'; $user->email = 'odonto1354@gmail.com'; $user->password = bcrypt('12345678'); $user->save();
        // $user = new User; $user->id = '8741'; $user->name = 'GIRALDO KELLY'; $user->email = 'odonto8741@gmail.com'; $user->password = bcrypt('12345678'); $user->save();
        // $user = new User; $user->id = '375'; $user->name = 'LOZANO LUZ DARY'; $user->email = 'odonto375@gmail.com'; $user->password = bcrypt('12345678'); $user->save();
        // $user = new User; $user->id = '371'; $user->name = 'HERNANDEZ KELLY'; $user->email = 'odonto371@gmail.com'; $user->password = bcrypt('12345678'); $user->save();
        // $user = new User; $user->id = '323'; $user->name = 'JIMENEZ DANIELA'; $user->email = 'odonto323@gmail.com'; $user->password = bcrypt('12345678'); $user->save();
        // $user = new User; $user->id = '324'; $user->name = 'CASTAÃ‘O DAVID'; $user->email = 'odonto324@gmail.com'; $user->password = bcrypt('12345678'); $user->save();
        // $user = new User; $user->id = '376'; $user->name = 'OSORIO MARIA JOSE'; $user->email = 'odonto376@gmail.com'; $user->password = bcrypt('12345678'); $user->save();
        // $user = new User; $user->id = '377'; $user->name = 'GUZMAN M LAURA'; $user->email = 'odonto377@gmail.com'; $user->password = bcrypt('12345678'); $user->save();
        // $user = new User; $user->id = '378'; $user->name = 'MARTINEZ MARCELA'; $user->email = 'odonto378@gmail.com'; $user->password = bcrypt('12345678'); $user->save();
        // $user = new User; $user->id = '395'; $user->name = 'GARCIA GIOVANNA'; $user->email = 'odonto395@gmail.com'; $user->password = bcrypt('12345678'); $user->save();
        // $user = new User; $user->id = '379'; $user->name = 'OCAMPO CAMILA'; $user->email = 'odonto379@gmail.com'; $user->password = bcrypt('12345678'); $user->save();
        // $user = new User; $user->id = '380'; $user->name = 'SALAZAR MARIO'; $user->email = 'odonto380@gmail.com'; $user->password = bcrypt('12345678'); $user->save();
        // $user = new User; $user->id = '399'; $user->name = 'NAVARRETE ANDRES'; $user->email = 'odonto399@gmail.com'; $user->password = bcrypt('12345678'); $user->save();
        // $user = new User; $user->id = '497'; $user->name = 'AGUILERA SARA'; $user->email = 'odonto497@gmail.com'; $user->password = bcrypt('12345678'); $user->save();
        // $user = new User; $user->id = '498'; $user->name = 'MEJIA DANNA VANESSA'; $user->email = 'odonto498@gmail.com'; $user->password = bcrypt('12345678'); $user->save();
        // $user = new User; $user->id = '499'; $user->name = 'SERRANO OSCAR'; $user->email = 'odonto499@gmail.com'; $user->password = bcrypt('12345678'); $user->save();
        // $user = new User; $user->id = '500'; $user->name = 'CRUZ VALENTINA'; $user->email = 'odonto500@gmail.com'; $user->password = bcrypt('12345678'); $user->save();
        // $user = new User; $user->id = '501'; $user->name = 'GUZMAN ALEJANDRA'; $user->email = 'odonto501@gmail.com'; $user->password = bcrypt('12345678'); $user->save();
        // $user = new User; $user->id = '502'; $user->name = 'CARLOSAMA ANABELY'; $user->email = 'odonto502@gmail.com'; $user->password = bcrypt('12345678'); $user->save();
        // $user = new User; $user->id = '504'; $user->name = 'ZAMORA CAROLINA'; $user->email = 'odonto504@gmail.com'; $user->password = bcrypt('12345678'); $user->save();
        // $user = new User; $user->id = '506'; $user->name = 'BRAND ANGELICA'; $user->email = 'odonto506@gmail.com'; $user->password = bcrypt('12345678'); $user->save();
        // $user = new User; $user->id = '507'; $user->name = 'RAMIREZ BEATRIZ'; $user->email = 'odonto507@gmail.com'; $user->password = bcrypt('12345678'); $user->save();
        // $user = new User; $user->id = '874'; $user->name = 'GARCIA DANIELA'; $user->email = 'odonto874@gmail.com'; $user->password = bcrypt('12345678'); $user->save();
        // $user = new User; $user->id = '756'; $user->name = 'AGUIRRE VALLEJO SEBASTIAN'; $user->email = 'odonto756@gmail.com'; $user->password = bcrypt('12345678'); $user->save();
        // $user = new User; $user->id = '503'; $user->name = 'CHICA LAURA'; $user->email = 'odonto503@gmail.com'; $user->password = bcrypt('12345678'); $user->save();
        // $user = new User; $user->id = '548'; $user->name = 'ARIAS LUZ ADELAIDA'; $user->email = 'odonto548@gmail.com'; $user->password = bcrypt('12345678'); $user->save();
        // $user = new User; $user->id = '459'; $user->name = 'MARIO PLAZA'; $user->email = 'odonto459@gmail.com'; $user->password = bcrypt('12345678'); $user->save();
        // $user = new User; $user->id = '565'; $user->name = 'PALACIO ALEJANDRO'; $user->email = 'odonto565@gmail.com'; $user->password = bcrypt('12345678'); $user->save();
        // $user = new User; $user->id = '984'; $user->name = 'REYES ERICKA GABRIELA'; $user->email = 'odonto984@gmail.com'; $user->password = bcrypt('12345678'); $user->save();
        // $user = new User; $user->id = '505'; $user->name = 'ESTRELLA YESSY C.'; $user->email = 'odonto505@gmail.com'; $user->password = bcrypt('12345678'); $user->save();
        // $user = new User; $user->id = '508'; $user->name = 'GUEVARA MANUELA'; $user->email = 'odonto508@gmail.com'; $user->password = bcrypt('12345678'); $user->save();
        // $user = new User; $user->id = '591'; $user->name = 'REMOLINA BEATRIZ'; $user->email = 'odonto591@gmail.com'; $user->password = bcrypt('12345678'); $user->save();
        // $user = new User; $user->id = '593'; $user->name = 'BAÃ‘OL NATALIA'; $user->email = 'odonto593@gmail.com'; $user->password = bcrypt('12345678'); $user->save();
        // $user = new User; $user->id = '594'; $user->name = 'GUEVARA MARIANA'; $user->email = 'odonto594@gmail.com'; $user->password = bcrypt('12345678'); $user->save();
        // $user = new User; $user->id = '595'; $user->name = 'MUÃ‘OZ MARIA JOSE'; $user->email = 'odonto595@gmail.com'; $user->password = bcrypt('12345678'); $user->save();
        // $user = new User; $user->id = '596'; $user->name = 'LARA ANDRES'; $user->email = 'odonto596@gmail.com'; $user->password = bcrypt('12345678'); $user->save();
        // $user = new User; $user->id = '598'; $user->name = 'LASSO ISABELLA'; $user->email = 'odonto598@gmail.com'; $user->password = bcrypt('12345678'); $user->save();
        // $user = new User; $user->id = '599'; $user->name = 'NASU FUJIE'; $user->email = 'odonto599@gmail.com'; $user->password = bcrypt('12345678'); $user->save();
        // $user = new User; $user->id = '597'; $user->name = 'CHALA LUISA FERNANDA'; $user->email = 'odonto597@gmail.com'; $user->password = bcrypt('12345678'); $user->save();
        // $user = new User; $user->id = '600'; $user->name = 'ESCOBAR GUZMAN JAIRO MAURICIO'; $user->email = 'odonto600@gmail.com'; $user->password = bcrypt('12345678'); $user->save();
        // $user = new User; $user->id = '601'; $user->name = 'CALLE OROZCO VANESA'; $user->email = 'odonto601@gmail.com'; $user->password = bcrypt('12345678'); $user->save();
        // $user = new User; $user->id = '509'; $user->name = 'TAPIA LINA MARCELA'; $user->email = 'odonto509@gmail.com'; $user->password = bcrypt('12345678'); $user->save();
        // $user = new User; $user->id = '328'; $user->name = 'LEON ISABEL'; $user->email = 'odonto328@gmail.com'; $user->password = bcrypt('12345678'); $user->save();
        // $user = new User; $user->id = '754'; $user->name = 'GIL DIEGO'; $user->email = 'odonto754@gmail.com'; $user->password = bcrypt('12345678'); $user->save();
        // $user = new User; $user->id = '521'; $user->name = 'CIFUENTES DARIO'; $user->email = 'odonto521@gmail.com'; $user->password = bcrypt('12345678'); $user->save();
        // $user = new User; $user->id = '423'; $user->name = 'QUICENO PAOLA'; $user->email = 'odonto423@gmail.com'; $user->password = bcrypt('12345678'); $user->save();
        // $user = new User; $user->id = '547'; $user->name = 'OBONAGA SANTIAGO'; $user->email = 'odonto547@gmail.com'; $user->password = bcrypt('12345678'); $user->save();
        // $user = new User; $user->id = '748'; $user->name = 'WAGNER ANDRES'; $user->email = 'odonto748@gmail.com'; $user->password = bcrypt('12345678'); $user->save();
        // $user = new User; $user->id = '545'; $user->name = 'LOPEZ ARIZA SUSAN ANDREA'; $user->email = 'odonto545@gmail.com'; $user->password = bcrypt('12345678'); $user->save();
        // $user = new User; $user->id = '413'; $user->name = 'ALZATE MARIA DE LOS ANGELES'; $user->email = 'odonto413@gmail.com'; $user->password = bcrypt('12345678'); $user->save();
        // $user = new User; $user->id = '414'; $user->name = 'MENDEZ LUISA FERNANDA'; $user->email = 'odonto414@gmail.com'; $user->password = bcrypt('12345678'); $user->save();
        // $user = new User; $user->id = '415'; $user->name = 'OVALLE CAROLINA'; $user->email = 'odonto415@gmail.com'; $user->password = bcrypt('12345678'); $user->save();
        // $user = new User; $user->id = '416'; $user->name = 'MALDONADO JOSE DANIEL'; $user->email = 'odonto416@gmail.com'; $user->password = bcrypt('12345678'); $user->save();
        // $user = new User; $user->id = '417'; $user->name = 'USECHE HECTOR'; $user->email = 'odonto417@gmail.com'; $user->password = bcrypt('12345678'); $user->save();
        // $user = new User; $user->id = '418'; $user->name = 'CHICANGO G. LEIDY TATIANA'; $user->email = 'odonto418@gmail.com'; $user->password = bcrypt('12345678'); $user->save();
        // $user = new User; $user->id = '419'; $user->name = 'PIEDRAHITA OCAMPO ALEJANDRO'; $user->email = 'odonto419@gmail.com'; $user->password = bcrypt('12345678'); $user->save();
        // $user = new User; $user->id = '420'; $user->name = 'ZUÃ‘IGA DIANA'; $user->email = 'odonto420@gmail.com'; $user->password = bcrypt('12345678'); $user->save();
        // $user = new User; $user->id = '421'; $user->name = 'OVIYUZ JUAN DIEGO'; $user->email = 'odonto421@gmail.com'; $user->password = bcrypt('12345678'); $user->save();
        // $user = new User; $user->id = '422'; $user->name = 'JIMENEZ CAROLINA'; $user->email = 'odonto422@gmail.com'; $user->password = bcrypt('12345678'); $user->save();
        // $user = new User; $user->id = '424'; $user->name = 'ALVIS M. ALEJANDRA'; $user->email = 'odonto424@gmail.com'; $user->password = bcrypt('12345678'); $user->save();
        // $user = new User; $user->id = '525'; $user->name = 'SUAREZ GABRIEL'; $user->email = 'odonto525@gmail.com'; $user->password = bcrypt('12345678'); $user->save();
        // $user = new User; $user->id = '526'; $user->name = 'PEREA VEGA ALEJANDRA'; $user->email = 'odonto526@gmail.com'; $user->password = bcrypt('12345678'); $user->save();
        // $user = new User; $user->id = '527'; $user->name = 'LOZANO NATALIA'; $user->email = 'odonto527@gmail.com'; $user->password = bcrypt('12345678'); $user->save();
        // $user = new User; $user->id = '528'; $user->name = 'PANTOJA FERNANDA'; $user->email = 'odonto528@gmail.com'; $user->password = bcrypt('12345678'); $user->save();
        // $user = new User; $user->id = '4785'; $user->name = 'RENGIFO VALENCIA LEIDY'; $user->email = 'odonto4785@gmail.com'; $user->password = bcrypt('12345678'); $user->save();
        // $user = new User; $user->id = '578'; $user->name = 'RAMIREZ YENNY'; $user->email = 'odonto578@gmail.com'; $user->password = bcrypt('12345678'); $user->save();
        // $user = new User; $user->id = '8547'; $user->name = 'TRUJILLO ELIZABETH'; $user->email = 'odonto8547@gmail.com'; $user->password = bcrypt('12345678'); $user->save();
        // $user = new User; $user->id = '3587'; $user->name = 'ZAPATA YURLADIS'; $user->email = 'odonto3587@gmail.com'; $user->password = bcrypt('12345678'); $user->save();
        // $user = new User; $user->id = '21453'; $user->name = 'FERNANDEZ JHON JAIRO'; $user->email = 'odonto21453@gmail.com'; $user->password = bcrypt('12345678'); $user->save();
        // $user = new User; $user->id = '1236'; $user->name = 'CORAL NATALIA'; $user->email = 'odonto1236@gmail.com'; $user->password = bcrypt('12345678'); $user->save();
        // $user = new User; $user->id = '8541'; $user->name = 'JARAMILLO CATALINA'; $user->email = 'odonto8541@gmail.com'; $user->password = bcrypt('12345678'); $user->save();
        // $user = new User; $user->id = '988'; $user->name = 'VASQUEZ ANDRES'; $user->email = 'odonto988@gmail.com'; $user->password = bcrypt('12345678'); $user->save();
        // $user = new User; $user->id = '785'; $user->name = 'ROJAS VALENTINA'; $user->email = 'odonto785@gmail.com'; $user->password = bcrypt('12345678'); $user->save();
        // $user = new User; $user->id = '19987'; $user->name = 'NIETO GRAJALES ANDRES FELIPE'; $user->email = 'odonto19987@gmail.com'; $user->password = bcrypt('12345678'); $user->save();
        // $user = new User; $user->id = '8523'; $user->name = 'PARRA R. MAILY BEATRIZ'; $user->email = 'odonto8523@gmail.com'; $user->password = bcrypt('12345678'); $user->save();
        // $user = new User; $user->id = '7854'; $user->name = 'GUEVARA ANDREA'; $user->email = 'odonto7854@gmail.com'; $user->password = bcrypt('12345678'); $user->save();
        
        $user = new User;
        $user->name = 'Juan Felipe - Administrador';
        $user->email = 'pipe@gmail.com';
        $user->password = bcrypt('12345678');
        $user->is_staff = true;
        $user->pin = '0000';
        $user->save();

        $user = new User;
        $user->name = 'Andrea - Facturacion';
        $user->email = 'andrea@gmail.com';
        $user->password = bcrypt('12345678');
        $user->is_staff = true;
        $user->pin = '1234';
        $user->save();

        $user = new User;
        $user->name = 'Paola - Imagenes';
        $user->email = 'paola@gmail.com';
        $user->password = bcrypt('12345678');
        $user->is_staff = true;
        $user->pin = '1425';
        $user->save();

        $user = new User;
        $user->name = 'Diana - Manager';
        $user->email = 'diana@gmail.com';
        $user->password = bcrypt('12345678');
        $user->is_staff = true;
        $user->pin = '4321';

        $user->save();

    }
}
