version: '3.7'

networks:
  travellist:
    driver: bridge

services:
  mysql-db:
    image: mysql:5.7
    volumes:
      - ./data/db:/var/lib/mysql
    container_name: mysql-db
    ports:
      - 30369:3036
    environment:
      - MYSQL_ROOT_PASSWORD=12345678
      - MYSQL_DATABASE=rxportal2
      - MYSQL_USER=laravel
      - MYSQL_PASSWORD=12345678
    networks:
      - travellist

  laravel-app:
    build:
      context: '.'
      args:
        uid: ${UID}
    container_name: laravel-app
    ports:
      - 8009:80
    environment:
      - APACHE_RUN_USER=#1000
      - APACHE_RUN_GROUP=#1000
    volumes:
      - .:/var/www/html
    depends_on:
      - mysql-db
    networks:
      - travellist
