version: '3.2'
services:
  laravel-db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: 12345678
      MYSQL_DATABASE: rxdent2
      MYSQL_USER: laravel
      MYSQL_PASSWORD: 12345678
    ports:
      - 33069:3306
    volumes:
      - ./data/schemas/:/var/lib/mysql
    networks:
      laravel_prod_net:
        - ipv4_address: "192.168.0.70"
  laravel-prod:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - 8200:80
    volumes:
      - ./example-prod:/var/www
      - ./example-prod/public:/var/www/html
    networks:
      laravel_prod_net:
        - ipv4_address: "192.168.0.71"
    depends_on:
      - laravel-db
  networks:
    laravel_prod_net:
      driver: bridge
      ipam:
        driver: default
        config:
          - subnet: 192.168.0.0/24



